[package]
name = "tictactoe-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extism-pdk = "0.1.0"
serde = "1.0.148"
serde_json = "1.0.89"

[lib]
crate_type = ["cdylib"]
